FROM ubuntu:18.04


RUN echo "deb [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic main restricted universe multiverse \n\
deb-src [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic main restricted universe multiverse \n\
deb [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-updates main restricted universe multiverse \n\
deb-src [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-updates main restricted universe multiverse \n\
deb [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-backports main restricted universe multiverse \n\
deb-src [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-backports main restricted universe multiverse \n\
deb [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-security main restricted universe multiverse \n\
deb-src [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-security main restricted universe multiverse \n\
deb [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-proposed main restricted universe multiverse \n\
deb-src [trusted=true] https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ bionic-proposed main restricted universe multiverse" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates \
    && apt-get install -y --allow-downgrades --allow-change-held-packages \
    && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt-get install -y tzdata \
    && /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

RUN apt-get update && apt-get install -y apt-utils curl wget inetutils-ping git vim zip unzip
