FROM ubuntu:16.04

RUN apt-get update && apt-get install -y apt-transport-https ca-certificates \
    && apt-get install -y --allow-downgrades --allow-change-held-packages \
    && DEBIAN_FRONTEND=noninteractive TZ=Asia/Shanghai apt-get install -y tzdata \
    && /bin/cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime \
    && dpkg-reconfigure -f noninteractive tzdata

RUN echo "deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial main restricted \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-updates main restricted \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial universe \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-updates universe \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial multiverse \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-updates multiverse \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-backports main restricted universe multiverse \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-security main restricted \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-security universe \n\
deb [trusted=true] http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/ xenial-security multiverse" > /etc/apt/sources.list

RUN apt-get update && apt-get install -y apt-utils curl wget inetutils-ping git vim zip unzip
